// <auto-generated />
namespace CMS_Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modTblCompany_addColBusssinessHour : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modTblCompany_addColBusssinessHour));
        
        string IMigrationMetadata.Id
        {
            get { return "201806250710454_modTblCompany_addColBusssinessHour"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
