// <auto-generated />
namespace CMS_Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modTblEmployee_addColPosition_editColLevel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modTblEmployee_addColPosition_editColLevel));
        
        string IMigrationMetadata.Id
        {
            get { return "201806250759261_modTblEmployee_addColPosition_editColLevel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
